!!es.um.poa.scenarios.ScenarioConfig
name: "EscenarioEjemplo"
description: "Ejemplo para hacer una configuraci√≥n YAML"
clock:
  unitTimeMillis: 1000
  numUnitDay: 10
  numSimDays: 1
fishMarket:
  name: "Lonja"
  config: "configs/fishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "configs/buyerType1.yaml"
  - name: "Comprador2"
    config: "configs/buyerType1.yaml"
sellers:
  - name: "Vendedor1"
    config: "configs/sellerType1.yaml"
